name: build

on:
  push:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symfony: ['^2.7', '^3', '^4', '^5']
        composer: ['--prefer-lowest', '']
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Require Symfony dependencies
        run: composer require --no-update symfony/config:${{ matrix.symfony }} symfony/dependency-injection:${{ matrix.symfony }} symfony/http-kernel:${{ matrix.symfony }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get Composer cache dir
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{steps.date.outputs.date}}-${{ runner.os }}-${{ matrix.symfony }}${{ matrix.composer }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{steps.date.outputs.date}}-${{ runner.os }}-${{ matrix.symfony }}${{ matrix.composer }}-composer-

      - name: Update Composer dependencies
        run: composer update ${{ matrix.composer }} --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run PHP Code Sniffer
        run: composer run-script test:phpcs
        if: success()

      - name: Run PHP Stan
        run: composer run-script test:phpstan
        if: success() || failure()

      - name: Run PHP Unit
        run: composer run-script test:phpunit
        if: success() || failure()
